### ISSUE TITLE
Unable to run sample code :-/

### ISSUE THREAD

**Issue by afzal273** [traveloka/styled-modules#16]
Hello, I'm trying to run the sample code, but getting the following errors. Please tell me how to fix

```
ERROR  Failed to compile with 1 errors                                                                                              14:29:11

 error  in ./pages/index.js

Module parse failed: Unexpected token (11:23)
You may need an appropriate loader to handle this file type.
| import styles from '../components/styles/style.css';
|
| const _default = () => <_StyledModules styles={[{
|   __hash: styles.__hash,
|   __css: styles.__css

 @ multi ./pages/index.js

Error: Module build failed: SyntaxError: Unexpected token (7:6)

   5 |   static getInitialProps({ renderPage }) {
   6 |     return {
>  7 |       ...renderPage(),
     |       ^
   8 |       styles: flush(),
   9 |     };
  10 |   }

    at Object../pages/_document.js (/Users/user/Documentsg/test-styled-modules/.next/dist/bundles/pages/_document.js:78:7)
    at __webpack_require__ (/Users/user/Documentsg/test-styled-modules/.next/dist/bundles/pages/webpack:/webpack/bootstrap 42ed6974729c93e46948?2bcd:21:1)
    at Object.1 (/Users/user/Documentsg/test-styled-modules/.next/dist/bundles/pages/_document.js:85:18)
    at __webpack_require__ (/Users/user/Documentsg/test-styled-modules/.next/dist/bundles/pages/webpack:/webpack/bootstrap 42ed6974729c93e46948?2bcd:21:1)
    at module.exports../pages/_document.js (/Users/user/Documentsg/test-styled-modules/.next/dist/bundles/pages/webpack:/webpack/bootstrap 42ed6974729c93e46948?2bcd:68:1)
    at Object.<anonymous> (/Users/user/Documentsg/test-styled-modules/.next/dist/bundles/pages/_document.js:73:10)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at _callee3$ (/Users/user/Documentsg/test-styled-modules/node_modules/next/dist/server/render.js:131:99)
    at tryCatch (/Users/user/Documentsg/test-styled-modules/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/user/Documentsg/test-styled-modules/node_modules/regenerator-runtime/runtime.js:296:22)
Error: Module build failed: SyntaxError: Unexpected token (7:6)

   5 |   static getInitialProps({ renderPage }) {
   6 |     return {
>  7 |       ...renderPage(),
     |       ^
   8 |       styles: flush(),
   9 |     };
  10 |   }

    at Object../pages/_document.js (/Users/user/Documentsg/test-styled-modules/.next/dist/bundles/pages/_document.js:78:7)
    at __webpack_require__ (/Users/user/Documentsg/test-styled-modules/.next/dist/bundles/pages/webpack:/webpack/bootstrap 42ed6974729c93e46948?2bcd:21:1)
    at Object.1 (/Users/user/Documentsg/test-styled-modules/.next/dist/bundles/pages/_document.js:85:18)
    at __webpack_require__ (/Users/user/Documentsg/test-styled-modules/.next/dist/bundles/pages/webpack:/webpack/bootstrap 42ed6974729c93e46948?2bcd:21:1)
    at module.exports../pages/_document.js (/Users/user/Documentsg/test-styled-modules/.next/dist/bundles/pages/webpack:/webpack/bootstrap 42ed6974729c93e46948?2bcd:68:1)
    at Object.<anonymous> (/Users/user/Documentsg/test-styled-modules/.next/dist/bundles/pages/_document.js:73:10)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at _callee3$ (/Users/user/Documentsg/test-styled-modules/node_modules/next/dist/server/render.js:131:99)
    at tryCatch (/Users/user/Documentsg/test-styled-modules/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/user/Documentsg/test-styled-modules/node_modules/regenerator-runtime/runtime.js:296:22)
(node:49247) DeprecationWarning: Module.chunks: Use Module.forEachChunk/mapChunks/getNumberOfChunks/isInChunk/addChunk/removeChunk instead
(node:49247) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Module parse failed: Unexpected token (4:22)
You may need an appropriate loader to handle this file type.
| import styles from '../components/styles/style.css';
|
| export default (() => <_StyledModules styles={[{
|   __hash: styles.__hash,
|   __css: styles.__css
(node:49247) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


 WAIT  Compiling...                                                                                                                  14:29:12



 ERROR  Failed to compile with 1 errors                                                                                              14:29:13

 error  in ./pages/index.js

Module parse failed: Unexpected token (11:23)
You may need an appropriate loader to handle this file type.
| import styles from '../components/styles/style.css';
|
| const _default = () => <_StyledModules styles={[{
|   __hash: styles.__hash,
|   __css: styles.__css

 @ multi ./pages/index.js
```
next.config.js
```
module.exports = {
  webpack: (config) => {
  config.module.rules.push(
    {
      test: /\.css$/,
      use: [
        'babel-loader',
        'styled-modules/loader',
        'css-loader?modules',
      ],
    },
  );
  return config;
  },
};
```

.babelrc
```
{
  "plugins": [
    ["styled-modules/babel", {
      "pattern": "\\.css$"
    }]
  ]
}
```
_document.js
```
import Document from 'next/document';
import flush from 'styled-modules/server';

class MyDocument extends Document {
  static getInitialProps({ renderPage }) {
    return {
      ...renderPage(),
      styles: flush(),
    };
  }
}

export default MyDocument;
```

index.js
```
import styles from '../components/styles/style.css';

export default () => (
  <div>
    <h1 className={styles.title}>Styled Modules</h1>
    <ol>
      {[
        'Item 1',
        'Item 2',
        'Item 3'
      ].map((item, index) => (
        <li key={index}>{item}</li>
      ))}
    </ol>
  </div>
);
```

style.css
```
.title {
  color: green;
  font-size: 4em;
}
```
package.json
```
{
  "name": "test-styled-modules",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "next"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "css-loader": "^0.28.11",
    "next": "^5.0.1-canary.17",
    "react": "^16.3.2",
    "react-dom": "^16.3.2",
    "styled-modules": "^0.2.4"
  }
}
```

**Comment by sayuti-daniel** [comment]
Hi @afzal273, as you can see the error message shown is a syntax error unable to parse object spread operator. Thus, you need a plugin to transform it or just use babel preset which include the transformer like the following.

```diff
{
+ “preset”: “next/babel”,
  "plugins": [
    ["styled-modules/babel", {
      "pattern": "\\.css$"
    }]
  ]
}
```

**Comment by sayuti-daniel** [comment]
That's because the style is rendered on client-side. You can do server-side rendering to solve the issue. It is already documented.
